INSERT INTO brands (name, country) VALUES
('APPLE','USA'),
('SAMSUNG','SOUTH KOREA'),
('XIAOMI','CHINA'),
('ONE PLUS','CHINA'),
('NOKIA','FINLAND'),
('LG','SOUTH KOREA'),
('TEXET','GREAT BRITAIN'),
('INOI','RUSSIAN FEDERATION'),
('OPPO','CHINA'),
('GOOGLE PIXEL','USA'),
('SONY','JAPAN'),
('VIVO','CHINA');
